# Generated by Django 4.2.6 on 2023-11-18 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disabled_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=2)),
                ('sex', models.CharField(choices=[('1', 'Kobieta'), ('2', 'Mężczyzna')], default='green', max_length=6)),
                ('city', models.CharField(max_length=200)),
                ('disability_type', models.CharField(max_length=300)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_info',
                'verbose_name_plural': 'Users_info',
            },
        ),
    ]
